name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-04-18"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "b0f7928c-e027-47e4-bfac-eb32cfb49ed6"
